//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace centroDeportivo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int Id { get; set; }
        public int SocioId { get; set; }
        public int ActividadId { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public virtual Socios Socios { get; set; }
    }
}
